#--------------------------------------------
# simple Makefile for java program
#
# note: indented lines must be TABs
#
Strings.class:		Strings.java
					javac *.java
#
run:
		java Strings
#
clean:
			rm -f *.class
#--------------------------------------------

