#--------------------------------------------
# simple Makefile for java program
#
# note: indented lines must be TABs
#
Driver.class:		Driver.java
					javac *.java
#
run:
		java Driver
#
clean:
			rm -f *.class
#--------------------------------------------

